/**
 * Generated by scripts/sync-brain-fusion.mjs from docs/brain.md (§9a).
 * Do not hand-edit — run `pnpm brain:sync` after changing the JSON block.
 */
/* eslint-disable */

export const BRAIN_FUSION_CALIBRATION_VERSION = 1 as const;
export const BRAIN_AJI_CHAT_BRIDGE = "aji_fusion: chat layer — NL contrast is exercised through Undercover/Slavic TS gates; CV/OSC Aji bridge stays research-only (alchemist-aji-fluidic), not web preset bytes";

export const BRAIN_HEALTH_FUSION = {
  HEALTH_WASM: "aji_fusion: browser export off — build packages/fxp-encoder wasm; GET /api/health/wasm should be available before promising .fxp",
  HEALTH_TRIAD_OFF: "aji_fusion: triad routes unconfigured — set provider keys; stub fetcher preserves gate identity but is not production sound",
  HEALTH_TRIAD_PARTIAL: "aji_fusion: partial triad — Hermes velocity is API wall time only; complete 3/3 for full governance blend",
  HEALTH_NOMINAL: "aji_fusion: health nominal — extra mile: verify:harsh after triad/export edits; parity stub===fetcher for gates",
} as const;

export const BRAIN_TALENT_INSUFFICIENT = "aji_fusion: talent scout needs panelistHealth or triadHealthScore — benchmarks are operator-maintained; no auto model swap";
export const BRAIN_TALENT_GAP_TEMPLATE = "aji_fusion: market gap flagged (Δ {{gap}}) — review {{weakest}} routing manually; deployer-owned configuration";
export const BRAIN_TALENT_NOMINAL = "aji_fusion: talent nominal — market rows are hints; triad weights stay canonical until product changes";

export const BRAIN_TAXONOMY_POOL_BOUND_TEMPLATE = "aji_fusion: taxonomy pool {{size}} > {{max}} — narrow offline before Slavic path; keep pre-Slavic n bounded (scoreCandidates cost)";

export const BRAIN_ARBITRATION_AGENT_AJI_FUSION_LINES = [
  "aji_fusion: transparent arbitration — 2-of-3 deterministic stages, full logEvent trail; no Slavic bypass",
] as const;

export const BRAIN_MOBILE_SHELL_LINE = "aji_fusion: mobile shell — triad and WASM export live on web-app; this surface is operator stance until API parity ships";

export const BRAIN_GREAT_LIBRARY_AGL_TEMPLATE = "aji_fusion: AGL merge keys [{{appliedKeys}}] — provenance \"{{provenance}}\"";

export const BRAIN_SOE_THRESHOLDS = {
  stubHeavyFusion: 0.35,
  triadFailureForKeysHint: 0.2,
  triadFailureForRelax: 0.25,
  gateDropForTighten: 0.55,
  triadFailureCeilingForTighten: 0.15,
  dualStressFailure: 0.25,
  dualStressGateDrop: 0.55,
  meanPanelistMsLatency: 6500,
  meanRunMsLatency: 20000,
  defaultPromptMax: 2000,
  latencySuggestedPromptMax: 1200,
} as const;

export const BRAIN_SOE_RECOMMENDATION_MESSAGES = {
  nominal: "soe: nominal — within heuristic bands",
  elevatedFailure: "soe: elevated triad failure rate — check provider health, timeouts, keys; consider relaxing entropy floor if results are empty",
  heavyGateDrop: "soe: heavy post-gate drop — Undercover/Slavic/adversarial stripping most candidates; review model or gate thresholds",
  highLatency: "soe: high latency — consider shorter prompts (suggested max chars lowered) or faster providers",
  stressed: "soe: stressed — high failures and high gate drop; triage API errors before tuning gates",
} as const;

export const BRAIN_SOE_FUSION_HINTS = {
  STUB_PROD_PARITY: "soe_fusion: stub-heavy telemetry — parity risk: verify:keys, test:real-gates; never treat stub as prod (security posture; gate identity stub===fetcher)",
  KEYS_AND_TIMEOUTS: "soe_fusion: triad failures — check keys, provider health, 8s / Qwen timeouts before retuning gates (degraded-infra + clear inputs)",
  GATE_SOURCE_QC: "soe_fusion: heavy gate drop — review prompt specificity + model output; source-hygiene for the pipeline, not silent Slavic/Undercover bypass",
  API_CONSTRAINT_ENTROPY: "soe_fusion: API strain — entropy relax is ops-only after empty-run proof; Undercover/Slavic must behave identically stub vs fetcher",
  STRESSED_DUAL: "soe_fusion: dual stress — high failures + high gate drop; triage API/keys before tuning entropy or gates (matches SOE stressed message)",
  LATENCY_PROMPT_UX: "soe_fusion: latency — shorter prompts + honest UI wait state (async expectation; not fake instant triad)",
  GOVERNANCE_VELOCITY: "soe_fusion: governance velocity stress — read wall time vs gate-drop together; ATHENA SOE path is telemetry governance, not buffer DSP",
  NOMINAL_VERIFY_MILE: "soe_fusion: nominal — extra mile: harshcheck on triad touches; document WASM + offset validation in PRs; agent tone after canon",
} as const;

export function formatBrainTalentGapFusionLine(gapFixed: string, weakest: string): string {
  return BRAIN_TALENT_GAP_TEMPLATE.replace(/\{\{gap\}\}/g, gapFixed).replace(/\{\{weakest\}\}/g, weakest);
}

export function formatBrainTaxonomyPoolBoundFusion(size: number, max: number): string {
  return BRAIN_TAXONOMY_POOL_BOUND_TEMPLATE.replace(/\{\{size\}\}/g, String(size)).replace(/\{\{max\}\}/g, String(max));
}

export function formatBrainGreatLibraryAglLine(appliedKeys: string, provenance: string): string {
  return BRAIN_GREAT_LIBRARY_AGL_TEMPLATE.replace(/\{\{appliedKeys\}\}/g, appliedKeys).replace(/\{\{provenance\}\}/g, provenance);
}

