/**
 * Generated by scripts/sync-igor-orchestrator.mjs from igor-power-cells.json.
 * Edit the JSON — run `pnpm igor:sync`. Do not hand-edit this file.
 */
/* eslint-disable */

export const IGOR_SHARED_ENGINE_POWER_CELLS_GEN = [
  {
    id: "triad",
    responsibility: "LLAMA/DEEPSEEK/QWEN fetch or stub; panel timing; gated scoring entry. triadPanelistSystemPrompt injects distinct PANELIST_DNA_SEED lines (ATHENA/HERMES/HESTIA vs wire ids) + elaboration; HARD GATE line forbids byte invention — verified triad-panelist-prompt.test.ts.",
    artifacts: ["triad.ts", "triad-monitor.ts", "candidate-finalizer.ts", "triad-constraint-injection.ts", "creative-diversity-layer.ts", "power-logic-fusion.ts", "arbitration/social-probe.ts", "triad-panelist-prompt.ts", "triad-panelist-system-prompt.ts", "explainability/decision-receipt.ts", "constants.ts", "circuit-breaker.ts", "triad-parity-report.ts"] as const,
  },
  {
    id: "gatekeeper",
    responsibility: "Telemetry purity — IQR/Z score stream + optional durationMs temporal gate.",
    artifacts: ["validate.ts"] as const,
  },
  {
    id: "slavic_score",
    responsibility: "Weighted ranking + cosine/text dedupe; creativePivot on dead end.",
    artifacts: ["score.ts", "intent-alignment.ts", "gates.ts"] as const,
  },
  {
    id: "undercover_adversarial",
    responsibility: "Distribution / adversarial statistical gates on candidates.",
    artifacts: ["validate.ts"] as const,
  },
  {
    id: "soe",
    responsibility: "SOE hints from triad health — telemetry only, not DSP buffers.",
    artifacts: ["soe.ts", "reality-signals-log.ts", "reality-loop-layer.ts", "rll/outcome-sink.ts", "iom-schism-impact.ts", "soe-hint-structured.ts"] as const,
  },
  {
    id: "agent_fusion",
    responsibility: "Brain §9a strings merged into operator-facing fusion lines.",
    artifacts: ["agent-fusion.ts", "brain-fusion-calibration.gen.ts"] as const,
  },
  {
    id: "integrity",
    responsibility: "Honest capability gaps, sprint completes, degraded fallbacks; WASM .fxp bridge; AIOM manifest layer.",
    artifacts: ["integrity.ts", "encoder.ts", "igor-orchestrator-layer.ts", "engine-valuation-heuristic.ts", "fxp-provenance.ts"] as const,
  },
  {
    id: "cyclic_integrity",
    responsibility: "Alchemist Core Model v1.0 — Z*29 state machine; Dual-Base Resonance (Binary/Decimal); Miller-compliant SAFE-7 mode; degradation triggers.",
    artifacts: ["core-model.ts", "integrity.ts", "iom-pulse.ts"] as const,
  },
  {
    id: "aji_entropy",
    responsibility: "Deterministic seed generation and signature-based entropy analysis for parameter randomization. Does not influence DSP or Gate logic.",
    artifacts: ["entropy.ts", "aji-logic.ts"] as const,
  },
  {
    id: "schism",
    responsibility: "Bipolar sprint stance (CONSOLIDATE vs DISRUPT) — narrative, logs, and AIOM pulse schisms only; does not mutate triad weights, TS gates, encoder bytes, or HARD GATE.",
    artifacts: ["schism.ts", "iom-pulse.ts", "iom-coverage.ts", "execution-tiers.ts"] as const,
  },
  {
    id: "triad_governance",
    responsibility: "ATHENA/HERMES/HESTIA blend weights + velocity from wall time.",
    artifacts: ["triad-panel-governance.ts"] as const,
  },
  {
    id: "arbitration",
    responsibility: "Transparent 2-of-3 arbitration — full logEvent trail.",
    artifacts: ["arbitration/transparent-arbitration.ts", "arbitration/types.ts"] as const,
  },
  {
    id: "taxonomy",
    responsibility: "Preset taxonomy pool narrow + sparse rank pre-Slavic.",
    artifacts: ["taxonomy/engine.ts", "taxonomy/prompt-keyword-sparse.ts", "taxonomy/sparse-rank.ts", "taxonomy/safe-process.ts"] as const,
  },
  {
    id: "talent_market",
    responsibility: "Market scout hints — deployer-owned benchmarks.",
    artifacts: ["talent/market-scout.ts"] as const,
  },
  {
    id: "tablebase",
    responsibility: "Deterministic short-circuit candidates when tablebase hits; offline learning types + prompt fingerprint.",
    artifacts: ["reliability/checkers-fusion.ts", "reliability/tablebase-db.ts", "reliability/tablebase-schema.ts", "reliability/prompt-fingerprint.ts", "learning/great-library.ts", "learning/offline-pipeline-types.ts"] as const,
  },
  {
    id: "perf_boss",
    responsibility: "FIRE-compliant perf sweep — perf_boss_* JSON on stderr.",
    artifacts: ["perf/compliant-perf-boss.ts"] as const,
  },
  {
    id: "prompt_guard",
    responsibility: "Triad prompt bounds, intent guard (`validateTriadIntent`), and rejection reasons.",
    artifacts: ["prompt-guard.ts", "intent-hardener.ts", "pnh/pnh-triad-defense.ts"] as const,
  },
  {
    id: "pnh",
    responsibility: "Predictive Network Hardening: deterministic ghost probes, APT-pattern catalog, immunity ledger. No runtime auto-patch. Triad HTTP rate limit lives in web-app; stderr redaction in telemetry-redact.ts.",
    artifacts: ["pnh/pnh-ghost-run.ts", "pnh/pnh-adaptive.ts", "pnh/pnh-attack-memory.ts", "pnh/immunity-ledger.ts", "pnh/pnh-context-evaluator.ts", "pnh/pnh-context-types.ts", "pnh/pnh-decision-with-memory.ts", "pnh/pnh-health-snapshot.ts", "pnh/pnh-proposal-model.ts", "pnh/pnh-simulation-engine.ts", "pnh/pnh-scenarios.ts", "pnh/pnh-triad-defense.ts", "pnh/pnh-triage-matrix.ts", "pnh/pnh-wargame.ts", "pnh/pnh-warfare-model.ts", "pnh/pnh-apt-prompt-scan.ts", "pnh/pnh-apt-scenarios.ts", "pnh/triad-rate-limit-core.ts", "telemetry-redact.ts"] as const,
  },
  {
    id: "vst_observer",
    responsibility: "VST/Serum trial preset bridge — diagnostic pulse + operator/CLI; HARD GATE before any .fxp bytes; optional surgical-repair clamps; encoder push path in packages/fxp-encoder/vst-bridge.ts (AIOM artifacts stay under shared-engine per sync script).",
    artifacts: ["vst-observer.ts", "iom-pulse.ts", "surgical-repair.ts"] as const,
  },
  {
    id: "vst_wrapper",
    responsibility: "JUCE VST3 FXP bridge skeleton (apps/vst-wrapper) — read-only consumer of validated .fxp; stores chunk as plugin state; does not inject Serum. Pulse: vst-wrapper-pulse.ts.",
    artifacts: ["vst-wrapper-pulse.ts", "iom-pulse.ts"] as const,
  },
  {
    id: "preset_share",
    responsibility: "User-consented shareable preset pages — slug generation, score gate (≥0.85), OG metadata from real candidate fields, paramArray visual only (no .fxp bytes exposed).",
    artifacts: ["../../apps/web-app/lib/share-preset.ts", "../../apps/web-app/lib/preset-store.ts", "../../apps/web-app/app/presets/[slug]/page.tsx", "../../apps/web-app/app/api/presets/share/route.ts"] as const,
  },
  {
    id: "humanitarian_integrity",
    responsibility: "Life-safety AIOM extension: medical, evacuation, and hazard response integrity; drift hard-stops (SAFE-4/ZERO).",
    artifacts: ["integrity/humanitarian-integrity.ts"] as const,
  },
  {
    id: "mentor_grounding_core",
    responsibility: "Combined mentor grounding logic: Natalia (heavy grounding, boundaries, 'Зачем?') + Lyubchenko (sincere support, 'Bravo', progress recognition). Heaviest weighting (0.90) for high-energy ideation management.",
    artifacts: ["../../.cursor/skills/inner-circle-voice/SKILL.md", "../../docs/internal/inner-circle-agent.md"] as const,
  },
] as const;
