/**
 * Generated by scripts/sync-igor-orchestrator.mjs from igor-power-cells.json.
 * Edit the JSON — run `pnpm igor:sync`. Do not hand-edit this file.
 */
/* eslint-disable */

export const IGOR_SHARED_ENGINE_POWER_CELLS_GEN = [
  {
    id: "triad",
    responsibility: "LLAMA/DEEPSEEK/QWEN fetch or stub; panel timing; gated scoring entry.",
    artifacts: ["triad.ts", "triad-monitor.ts", "constants.ts"] as const,
  },
  {
    id: "gatekeeper",
    responsibility: "Telemetry purity — IQR/Z score stream + optional durationMs temporal gate.",
    artifacts: ["validate.ts"] as const,
  },
  {
    id: "slavic_score",
    responsibility: "Weighted ranking + cosine/text dedupe; creativePivot on dead end.",
    artifacts: ["score.ts", "gates.ts"] as const,
  },
  {
    id: "undercover_adversarial",
    responsibility: "Distribution / adversarial statistical gates on candidates.",
    artifacts: ["validate.ts"] as const,
  },
  {
    id: "soe",
    responsibility: "SOE hints from triad health — telemetry only, not DSP buffers.",
    artifacts: ["soe.ts"] as const,
  },
  {
    id: "agent_fusion",
    responsibility: "Brain §9a strings merged into operator-facing fusion lines.",
    artifacts: ["agent-fusion.ts", "brain-fusion-calibration.gen.ts"] as const,
  },
  {
    id: "integrity",
    responsibility: "Honest capability gaps, sprint completes, degraded fallbacks; WASM .fxp bridge; Igor manifest layer.",
    artifacts: ["integrity.ts", "encoder.ts", "igor-orchestrator-layer.ts"] as const,
  },
  {
    id: "aji_entropy",
    responsibility: "Entropy seeds + crystallized residue (TS-only distillation).",
    artifacts: ["entropy.ts", "aji-logic.ts"] as const,
  },
  {
    id: "schism",
    responsibility: "Bipolar sprint stance (CONSOLIDATE vs DISRUPT) — narrative + logs only; IOM pulse schisms.",
    artifacts: ["schism.ts", "iom-pulse.ts"] as const,
  },
  {
    id: "triad_governance",
    responsibility: "ATHENA/HERMES/HESTIA blend weights + velocity from wall time.",
    artifacts: ["triad-panel-governance.ts"] as const,
  },
  {
    id: "arbitration",
    responsibility: "Transparent 2-of-3 arbitration — full logEvent trail.",
    artifacts: ["arbitration/transparent-arbitration.ts", "arbitration/types.ts"] as const,
  },
  {
    id: "taxonomy",
    responsibility: "Preset taxonomy pool narrow + sparse rank pre-Slavic.",
    artifacts: ["taxonomy/engine.ts", "taxonomy/sparse-rank.ts"] as const,
  },
  {
    id: "talent_market",
    responsibility: "Market scout hints — deployer-owned benchmarks.",
    artifacts: ["talent/market-scout.ts"] as const,
  },
  {
    id: "tablebase",
    responsibility: "Deterministic short-circuit candidates when tablebase hits; offline learning types + prompt fingerprint.",
    artifacts: ["reliability/checkers-fusion.ts", "reliability/tablebase-db.ts", "reliability/tablebase-schema.ts", "reliability/prompt-fingerprint.ts", "learning/great-library.ts", "learning/offline-pipeline-types.ts"] as const,
  },
  {
    id: "perf_boss",
    responsibility: "FIRE-compliant perf sweep — perf_boss_* JSON on stderr.",
    artifacts: ["perf/compliant-perf-boss.ts"] as const,
  },
  {
    id: "prompt_guard",
    responsibility: "Triad prompt bounds and rejection reasons.",
    artifacts: ["prompt-guard.ts"] as const,
  },
  {
    id: "vst_observer",
    responsibility: "VST/Serum trial preset bridge — diagnostic pulse + operator/CLI; HARD GATE before any .fxp bytes; optional surgical-repair clamps; encoder push path in packages/fxp-encoder/vst-bridge.ts (Igor artifacts stay under shared-engine per sync script).",
    artifacts: ["vst-observer.ts", "iom-pulse.ts", "surgical-repair.ts"] as const,
  },
  {
    id: "vst_wrapper",
    responsibility: "JUCE VST3 FXP bridge skeleton (apps/vst-wrapper) — read-only consumer of validated .fxp; stores chunk as plugin state; does not inject Serum. Pulse: vst-wrapper-pulse.ts.",
    artifacts: ["vst-wrapper-pulse.ts", "iom-pulse.ts"] as const,
  },
] as const;
