/**
 * Generated by scripts/sync-igor-orchestrator.mjs from workspace package.json + igor-orchestrator-meta.json.
 * Do not hand-edit — run `pnpm igor:sync`.
 */
/* eslint-disable */

export const IGOR_ORCHESTRATOR_PACKAGES_GEN = [
  {
    packageName: "@alchemist/mobile-app",
    pathFromRepoRoot: "apps/mobile-app",
    role: "Expo shell — operator stance until API parity (brain fusion mobile line).",
    canonAnchors: ["brain-fusion-calibration mobile shell"] as const,
  },
  {
    packageName: "@alchemist/web-app",
    pathFromRepoRoot: "apps/web-app",
    role: "Next.js App Router — triad routes, health, Mercury UI, browser WASM export hook.",
    canonAnchors: ["FIRESTARTER §5a keys", "GET /api/health/*"] as const,
  },
  {
    packageName: "@alchemist/fxp-encoder",
    pathFromRepoRoot: "packages/fxp-encoder",
    role: "Rust→WASM Serum preset bytes — behind validated serum-offset-map (HARD GATE).",
    canonAnchors: ["alchemist-brief.mdc HARD GATE", "tools/validate-offsets.py"] as const,
  },
  {
    packageName: "@alchemist/serum2-encoder",
    pathFromRepoRoot: "packages/serum2-encoder",
    role: "Serum 2 encode path — same offset discipline as fxp-encoder family.",
    canonAnchors: ["HARD GATE", "FIRE.md encoder notes"] as const,
  },
  {
    packageName: "@alchemist/shared-engine",
    pathFromRepoRoot: "packages/shared-engine",
    role: "Preset logic, triad, TS gates (Undercover/Slavic), SOE, integrity, Aji, schism, perf boss, arbitration.",
    canonAnchors: ["FIRESTARTER §6", "alchemist-dsp-vs-ts-gates.mdc", "brain.md §9a fusion"] as const,
  },
  {
    packageName: "@alchemist/shared-types",
    pathFromRepoRoot: "packages/shared-types",
    role: "Schema source of truth — AICandidate, SerumState, panelist IDs.",
    canonAnchors: ["AGENTS.md", "alchemist-brief.mdc build order"] as const,
  },
  {
    packageName: "@alchemist/shared-ui",
    pathFromRepoRoot: "packages/shared-ui",
    role: "Shared React/Tailwind surfaces for web + future shells.",
    canonAnchors: ["design tokens", "web-app consumer"] as const,
  },
] as const;
