/**
 * Generated by scripts/sync-igor-orchestrator.mjs from igor-power-cells.json.
 * Edit the JSON — run `pnpm igor:sync`. Do not hand-edit this file.
 */
/* eslint-disable */

export const IGOR_SHARED_ENGINE_POWER_CELLS_GEN = [
  {
    id: "triad",
    responsibility: "LLAMA/DEEPSEEK/QWEN fetch or stub; panel timing; gated scoring entry.",
    artifacts: ["triad.ts", "triad-monitor.ts", "constants.ts"] as const,
  },
  {
    id: "gatekeeper",
    responsibility: "Telemetry purity — IQR/Z score stream + optional durationMs temporal gate.",
    artifacts: ["validate.ts"] as const,
  },
  {
    id: "slavic_score",
    responsibility: "Weighted ranking + cosine/text dedupe; creativePivot on dead end.",
    artifacts: ["score.ts", "gates.ts"] as const,
  },
  {
    id: "undercover_adversarial",
    responsibility: "Distribution / adversarial statistical gates on candidates.",
    artifacts: ["validate.ts"] as const,
  },
  {
    id: "soe",
    responsibility: "SOE hints from triad health — telemetry only, not DSP buffers.",
    artifacts: ["soe.ts"] as const,
  },
  {
    id: "agent_fusion",
    responsibility: "Brain §9a strings merged into operator-facing fusion lines.",
    artifacts: ["agent-fusion.ts", "brain-fusion-calibration.gen.ts"] as const,
  },
  {
    id: "integrity",
    responsibility: "Honest capability gaps, sprint completes, degraded fallbacks.",
    artifacts: ["integrity.ts"] as const,
  },
  {
    id: "aji_entropy",
    responsibility: "Entropy seeds + crystallized residue (TS-only distillation).",
    artifacts: ["entropy.ts", "aji-logic.ts"] as const,
  },
  {
    id: "schism",
    responsibility: "Bipolar sprint stance (CONSOLIDATE vs DISRUPT) — narrative + logs only.",
    artifacts: ["schism.ts"] as const,
  },
  {
    id: "triad_governance",
    responsibility: "ATHENA/HERMES/HESTIA blend weights + velocity from wall time.",
    artifacts: ["triad-panel-governance.ts"] as const,
  },
  {
    id: "arbitration",
    responsibility: "Transparent 2-of-3 arbitration — full logEvent trail.",
    artifacts: ["arbitration/transparent-arbitration.ts"] as const,
  },
  {
    id: "taxonomy",
    responsibility: "Preset taxonomy pool narrow + sparse rank pre-Slavic.",
    artifacts: ["taxonomy/engine.ts", "taxonomy/sparse-rank.ts"] as const,
  },
  {
    id: "talent_market",
    responsibility: "Market scout hints — deployer-owned benchmarks.",
    artifacts: ["talent/market-scout.ts"] as const,
  },
  {
    id: "tablebase",
    responsibility: "Deterministic short-circuit candidates when tablebase hits.",
    artifacts: ["reliability/checkers-fusion.ts", "reliability/tablebase-db.ts"] as const,
  },
  {
    id: "perf_boss",
    responsibility: "FIRE-compliant perf sweep — perf_boss_* JSON on stderr.",
    artifacts: ["perf/compliant-perf-boss.ts"] as const,
  },
  {
    id: "prompt_guard",
    responsibility: "Triad prompt bounds and rejection reasons.",
    artifacts: ["prompt-guard.ts"] as const,
  },
] as const;
